services:
  - mongo

## Cache composer packages between all jobs and all branches
## of this project...
cache:
  key: one-key-to-rull-them-all
  paths:
    - composer-cache/

.phptest:
  before_script:
    # Install all project dependencies
    - cd web
    - COMPOSER_CACHE_DIR=../composer-cache composer install
    # setup Laravel
    - cp env.test .env
    - touch storage/app/db.sqlite
    - php artisan migrate


# Test with PHP7.2 
test:php72:
  extends: .phptest
  image: cylab/php72
  script:
    - vendor/bin/phpunit --coverage-text
    - vendor/bin/phpcs

test:gitleaks:
  image: 
    name: "zricethezav/gitleaks"
    entrypoint: [""]
  script:
    - gitleaks -v --repo-path=./ --config=gitleaks.toml
