# https://hub.docker.com/_/php/
image: php:7.2

before_script:
  # Install git, the php image doesn't have installed
  - apt-get update -yqq
  - apt-get install git -yqq
  # Install composer
  - curl -sS https://getcomposer.org/installer | php
  # Install PHP-ZIP extension (used by composer)
  - apt-get install -yqq libzip-dev
  - docker-php-ext-install zip
  # Install xdebug extension (used for phpunit code coverage)
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - pecl install mongodb-1.4.4
  - docker-php-ext-enable mongodb
  # Install all project dependencies
  - cd web
  - php ../composer.phar install
  # setup Laravel
  - cp env.test .env
  - touch storage/app/db.sqlite
  - php artisan migrate


# Test with PHP7 
test:php72:
  image: php:7.2
  script:
    - cd web && vendor/bin/phpunit --coverage-text
